/HFOSS is not a lawyer, and this does not constitute legal advice./

*Please select the most appropriate span of time for each of the
following [4pts in total]:*

1) The Bayh-Dole Act was passed, which gave rise to university
technology transfer offices; the GNU Project and Free Software
Foundation were founded; the US acceded to the international Berne
Convention on copyrights; software was explicitly covered by US federal
copyright law [ 1 pt]

a) 1960s b) 1970s c) 1980s d) 1990s e) 2000s f) 2010s

2) Creative Commons was founded. [1 pt]

a) 1960s b) 1970s c) 1980s d) 1990s e) 2000s f) 2010s

3) UNIX was published, Michael Hart started digitizing texts for what
became Project Gutenburg, and Bill Gates wrote his "Open Letter to
Hobbyists". [1 pt]

a) 1960s b) 1970s c) 1980s d) 1990s e) 2000s f) 2010s

4) Linus Torvalds started writing the Linux kernel, the Digital
Millenium Copyright Act was passed. [1 pt]

a) 1960s b) 1970s c) 1980s d) 1990s e) 2000s f) 2010s

*5) Several elements are combined in different ways to form the various
Creative Commons licenses.\\
Please match each shorthand given in the numbered list with the letter
next to the description of that license element below (2 pt for each
match).\\
*

-  5.1) NC \_\_\_
-  5.2) SA \_\_\_
-  5.3) ND \_\_\_
-  5.4) BY \_\_\_

-  A) You must convey the same rights "downstream" that were conveyed to
   you by "upstream".
-  B) You must attribute the contributions of the original or upstream
   creators of the work.
-  C) You may not use the work for commercial purposes.
-  D) You may not make changes to the work.

*6) The presence of which license elements make a license "non-free" in
the eyes of the FSF? (give the letters, 1 pt XC each)*

*7) Which license element is a copyleft? (give the letter, 1 pt XC)*

*8) Name two projects which distribute a body of non-software, free
culture data, and briefly name or describe the kind of data. (1 pt XC
each)*

-  8.1)
-  8.2)

9) We've discussed "the four R's" as a shorthand for the freedoms
attached to software for it to be considered "free" or "open source".
*List or describe each.* (eg, if you can remember the "r" word you can
just give that. If you cannot remember the term, but can describe the
freedom involved, that also counts). Various "r" words are roughly
synonymous for some of the freedoms, but we're counting freedoms here,
not synonyms so if you give two (or more) terms for the same freedom, it
only counts once. For the purposes of this quiz, "remix" does not count
as describing any of them. (2pt each)\\
- 9.1) - 9.2) - 9.3) - 9.4)

**** Q: /How do I quiz?/

**** A: /3 Steps:/

1. Create a blog post that includes each question, with the answer to
   each question below it, on your HFOSS Blog you set up in
   [[/hw/firstflight][/First Flight/]].
2. Add a line to the bottom of your .yaml file you edited in first
   flight, with the link to your post.
3. Send deejoe a pull request.

